// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3-0o-34Ld6QQwC3PgUidINL615CewYSU',
    appId: '1:934238205:web:6753f47a0f919eaaf3ab94',
    messagingSenderId: '934238205',
    projectId: 'chat-app-137e6',
    authDomain: 'chat-app-137e6.firebaseapp.com',
    databaseURL: 'https://chat-app-137e6-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-137e6.appspot.com',
    measurementId: 'G-SQ2LR4QLT7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyZOLxlz1_O3uzqLBoAfHWHLAC1Qogbd4',
    appId: '1:934238205:android:2c9cd2b030f5da76f3ab94',
    messagingSenderId: '934238205',
    projectId: 'chat-app-137e6',
    databaseURL: 'https://chat-app-137e6-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-137e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtyeFJaa6RZFw3ENeSIBw7PS5zsTvT9l8',
    appId: '1:934238205:ios:9d67a75030a4ff59f3ab94',
    messagingSenderId: '934238205',
    projectId: 'chat-app-137e6',
    databaseURL: 'https://chat-app-137e6-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-137e6.appspot.com',
    iosClientId: '934238205-si52279niad68ftq47fekp3t1o3kns2e.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtyeFJaa6RZFw3ENeSIBw7PS5zsTvT9l8',
    appId: '1:934238205:ios:9d67a75030a4ff59f3ab94',
    messagingSenderId: '934238205',
    projectId: 'chat-app-137e6',
    databaseURL: 'https://chat-app-137e6-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-137e6.appspot.com',
    iosClientId: '934238205-si52279niad68ftq47fekp3t1o3kns2e.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
